apiVersion: v1
kind: Pod
metadata:
  name: suse-server
  labels:
    app: suse-server
spec:
  containers:
  - name: suse-server
    image: ghcr.io/dbw7/demo-container:latest
    ports:
    - containerPort: 9977
---
apiVersion: v1
kind: Service
metadata:
  name: suse-server
  labels:
    app: suse-server
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9977
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app: suse-server